name: flutter_firebase_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cache:
    path: packages/cache
  equatable: ^2.0.3
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_staggered_grid_view: ^0.6.2
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_sign_in: ^5.4.0
  http: ^0.13.5
  meta: ^1.7.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
