// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBunzB7s692kKLWKERj1f3LqtrY5fG9Vos',
    appId: '1:952563975841:web:899ef0253f56ecda7b52e0',
    messagingSenderId: '952563975841',
    projectId: 'management-portal-f53bf',
    authDomain: 'management-portal-f53bf.firebaseapp.com',
    databaseURL:
        'https://management-portal-f53bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'management-portal-f53bf.appspot.com',
    measurementId: 'G-9EDSRPHMBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSFm6mkRYdAy-Z8_EXilCLGWfVE8392w',
    appId: '1:952563975841:android:ed90b4b18b8bf5db7b52e0',
    messagingSenderId: '952563975841',
    projectId: 'management-portal-f53bf',
    databaseURL:
        'https://management-portal-f53bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'management-portal-f53bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vOGdLGVD_QV3SLUu07zNfUSlpUhlc5U',
    appId: '1:952563975841:ios:fa1fa7e76f05f4e77b52e0',
    messagingSenderId: '952563975841',
    projectId: 'management-portal-f53bf',
    databaseURL:
        'https://management-portal-f53bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'management-portal-f53bf.appspot.com',
    iosClientId:
        '952563975841-f4hmplmsp9ssrdvrkpdumijo6dfvm1iq.apps.googleusercontent.com',
    iosBundleId: 'com.test.managementPortal',
  );
}
